### ISSUE TITLE
Where's the counter?

### ISSUE THREAD

**Issue by jfgodfrey** [nitsan-technologies/ns_statcounter#1]
I just installed the extension into my 8.7.24 typo3 cms backend.  I followed all the instructions in the manual, got my Project ID and Security Key from statcounter, and selected for the counter to appear in the header.  I also verified with statcounter and it said the project is working.  I can even see the stats from my checking things out.  However, there's no counter on the page.  Do I have to manually add other code?  I thought that if I selected: Add at Header, that that was all I needed to do to have it show up.

**Comment by nitsan-technologies** [comment]
Hey @jfgodfrey 

- Thanks for connecting with us. It seems you bit misunderstand, the plugin does not display "counter" kind of things at your site. It's just adding the tracking code ;)

- By d way, thanks for your nice idea to consider to release next major version of this extension, let us add such features from "statcounter.com" to display "counter" by configuring from TYPO3 backned.

- Quick question, How do you want to manage from TYPO3 backend? I mean, generally, where do you want to display such "counter". Is a simple frontend plugin works for your case?

Cheers,
Sanjay

**Comment by jfgodfrey** [comment]
Sanjay,
Thanks for your quick response.  You may ignore my email.  Yes, a frontend plugin would probably be fine.  If the config: Add at Header or Add at Footer doesn't show the counter, what is it for?

**Comment by nitsan-technologies** [comment]
Hey John,

**Frontend Plugin**
Cool, will do it in that way. Also, will try to provide TypoScript setup, so people have more flexibility to add anywhere in their templates ;)

**Header/Footer**
Actually that's just option to add JS code either before or after body tag. We will remove that unncessary option as you said, at footer does not work, probably statcoutner.com guys does not suppot it now.

Cheers,
Sanjay
